import { createContext, useContext } from 'react';

export const LangContext = createContext('zh');

export function useLang() {
  return useContext(LangContext);
}

// 所有 UI 文本的中英文翻译
export const T = {
  zh: {
    height: '高度',
    annotation: '尺寸',
    share: '分享',
    qr: '二维码',
    gallery: '画廊',
    material: '材质',
    accessory: '配件',
    cart: '购物车',
    consult: '咨询',
    rise: '上升',
    descend: '下降',
    expand: '展开高度',
    clickStop: '点击停止',
    releaseStop: '松手停止',
    rank1: '一档',
    rank2: '二档',
    rank3: '三档',
    mat_light: '浅胡桃色',
    mat_oak: '原木白橡',
    mat_dark: '深胡桃色',
    acc_cup: '杯架',
    acc_hook: '挂钩',
    acc_lamp: '台灯',
    scanQr: '扫码查看',
    brand: 'HE FURNITURE',
    sub: '智能升降桌',
    view: '查看',
    solo: '独显',
    orbit: '环绕',
    subBrand: '智能升降桌',
    viewBackground: '背景',
    video: '视频',
    cartTitle: '购物清单',
    cartBaseDesc: '智能升降桌 · 基础款',
    cartHeightDesc: '桌高 {h}cm 档位',
    cartMatDesc: '实木贴面工艺',
    cartAccDesc: '原厂配套',
    cartIncluded: '已包含',
    cartTotal: '合计',
    cartOrder: '立即下单',
    contactName: '姓名',
    contactTitle: '职位',
    contactPhone: '电话',
    contactWechat: '微信',
    contactAddress: '地址',
    contactQrCaption: '微信二维码',
    contactAdvisor: '产品顾问',
    noVideo: '暂无视频素材',
    mobileSelectMat: '选择材质',
    mobileSelectAcc: '选择配件',
    mobileSelectView: '查看选项',
    mobileSit: '坐姿',
    mobileStand: '标准',
    mobileHigh: '站立',
    mobileRise: '升高',
    mobileLower: '降低',
    mobileDimensions: '尺寸标注',
    mobileSolo: '独显模式',
    mobileOrbit: '360° 环绕',
    mobileGallery: '产品画廊',
    mobileStandard: '标准配色',
    mobileHeightFmt: '高度 · {h} cm',
  },
  en: {
    height: 'HEIGHT',
    annotation: 'INFO',
    share: 'SHARE',
    qr: 'QR',
    gallery: 'GALLERY',
    material: 'MATERIAL',
    accessory: 'ADD-ON',
    cart: 'CART',
    consult: 'CONTACT',
    rise: 'RISE',
    descend: 'LOWER',
    expand: 'ADJUST',
    clickStop: 'STOP',
    releaseStop: 'RELEASE',
    rank1: 'LOW',
    rank2: 'MID',
    rank3: 'HIGH',
    mat_light: 'LIGHT WALNUT',
    mat_oak: 'WHITE OAK',
    mat_dark: 'DARK WALNUT',
    acc_cup: 'CUP',
    acc_hook: 'HOOK',
    acc_lamp: 'LAMP',
    scanQr: 'Scan to view',
    brand: 'HE FURNITURE',
    sub: 'HEIGHT-ADJ DESK',
    view: 'VIEW',
    solo: 'SOLO',
    orbit: 'ORBIT',
    subBrand: 'HEIGHT-ADJ DESK',
    viewBackground: 'BG',
    video: 'VIDEO',
    cartTitle: 'Cart',
    cartBaseDesc: 'Smart Desk · Base',
    cartHeightDesc: 'Height {h} cm',
    cartMatDesc: 'Solid Wood Veneer',
    cartAccDesc: 'Genuine Parts',
    cartIncluded: 'Included',
    cartTotal: 'Total',
    cartOrder: 'Order Now',
    contactName: 'Name',
    contactTitle: 'Title',
    contactPhone: 'Phone',
    contactWechat: 'WeChat',
    contactAddress: 'Address',
    contactQrCaption: 'QR Code',
    contactAdvisor: 'Consultant',
    noVideo: 'No Video Available',
    mobileSelectMat: 'Material',
    mobileSelectAcc: 'Accessories',
    mobileSelectView: 'View Options',
    mobileSit: 'Sit',
    mobileStand: 'Standard',
    mobileHigh: 'Stand',
    mobileRise: 'Up',
    mobileLower: 'Down',
    mobileDimensions: 'Dimensions',
    mobileSolo: 'Solo Mode',
    mobileOrbit: '360° Orbit',
    mobileGallery: 'Gallery',
    mobileStandard: 'Standard',
    mobileHeightFmt: 'Height · {h} cm',
  },
};
